version: '3'

services:
  magjob-backend:
    image: keepitup2023/magjob-backend:latest
    restart: always
    depends_on:
      - pgadmin
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/master
      - SERVER-URL=http://keycloak:8080

  magjob-swagger-server-handler:
    image: keepitup2023/magjob-swagger-server-handler:latest
    restart: always
    depends_on:
      # comment if you want to use locally launched API
      - magjob-backend
    environment:
      # change if you want to use locally launched API
      # SWAGGER_URL: http://host.docker.internal:8080/v3/api-docs
      SWAGGER_URL: http://magjob-backend:8080/v3/api-docs
      WAIT_TIME: 2
    volumes:
      - ./MagJob-swagger-server/swagger.json:/swagger.json

  magjob-swagger-server:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - "6969:8080"
    depends_on:
      - magjob-swagger-server-handler
    environment:
      SWAGGER_JSON: /mnt/swagger.json
    volumes:
      - ./MagJob-swagger-server/swagger.json:/mnt/swagger.json

  magjob-frontend:
    image: keepitup2023/magjob-frontend:latest
    restart: always
    environment:
      API_URL: http://magjob-backend:8080/api
    ports:
      - "4200:80"
    depends_on:
      - magjob-backend

  keycloak:
    image: keepitup2023/magjob-keycloak:latest
    command: start-dev --import-realm -b=0.0.0.0
    environment:
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - ${APPDATA}/db/keycloak:/opt/keycloak/data
      - ./images/keycloak/magjob-realm.json:/opt/keycloak/data/import/magjob-realm.json

  db:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./MagJob-test-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4:2023-11-20-2
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./MagJob-test-data/pgadmin:/var/lib/pgadmin/data
    depends_on:
      - db

  prometheus:
    image: keepitup2023/magjob-prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - magjob-frontend

  grafana:
    image: keepitup2023/magjob-grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
