version: '3'

services:
  magjob-backend:
    image: magjob-backend:0.0.1
    restart: always
    depends_on:
      - pgadmin
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  magjob-frontend:
    image: magjob-frontend:0.0.1
    restart: always
    environment:
      API_URL: http://magjob-backend:8080/api
    ports:
      - "8080:80"
    depends_on:
      - magjob-backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "28080:8080"
      - "28443:8443"
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_USERNAME=${KC_DB_USER}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=localhost
      - KC_HTTPS_CERTIFICATE_FILE=./etc/ssl/certs/cert.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=./etc/ssl/certs/cert-key.pem
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
    volumes:
      - ./keycloak/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./keycloak/certs/cert-key.pem:/etc/ssl/certs/cert-key.pem
    depends_on:
      - keycloak-db
    command: start
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  keycloak-db:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
      - POSTGRES_USER=${KC_DB_USER}
      - POSTGRES_DB=keycloak
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  db:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  pgadmin:
    image: dpage/pgadmin4:2023-11-20-2
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin/data
    depends_on:
      - db
      - keycloak-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/etc/prometheus
    depends_on:
      - magjob-frontend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s

  volumes:
    data:
      driver_opts:
        type: none
        o: bind
        device: ./db/data
    keycloak-data:
      driver_opts:
        type: none
        o: bind
        device: ./db/keycloak-data
    pgadmin:
      driver_opts:
        type: none
        o: bind
        device: ./db/pgadmin
    prometheus:
      driver_opts:
        type: none
        o: bind
        device: ./monitoring/prometheus
    grafana:
      driver_opts:
        type: none
        o: bind
        device: ./monitoring/grafana/provisioning/datasources
