server.port=8081

spring.application.name=magjob-backend-auth

# Authorization Code Flow with PKCE for Angular
spring.security.oauth2.authorizationserver.client.angular.registration.client-id=angular-client
spring.security.oauth2.authorizationserver.client.angular.registration.authorization-grant-types[0]=authorization_code
spring.security.oauth2.authorizationserver.client.angular.registration.authorization-grant-types[1]=refresh_token
spring.security.oauth2.authorizationserver.client.angular.registration.client-authentication-methods[0]=none
spring.security.oauth2.authorizationserver.client.angular.registration.redirect-uris[0]=http://localhost:4200/
spring.security.oauth2.authorizationserver.client.angular.registration.redirect-uris[1]=http://localhost:4200
spring.security.oauth2.authorizationserver.client.angular.registration.redirect-uris[2]=http://localhost:4200/users
spring.security.oauth2.authorizationserver.client.angular.registration.redirect-uris[3]=http://localhost:4200/users/
spring.security.oauth2.authorizationserver.client.angular.registration.scopes[0]=openid
spring.security.oauth2.authorizationserver.client.angular.registration.scopes[1]=profile
spring.security.oauth2.authorizationserver.client.angular.registration.scopes[2]=email
spring.security.oauth2.authorizationserver.client.angular.registration.scopes[3]=read-write
spring.security.oauth2.authorizationserver.client.angular.require-proof-key=true

logging.level.org.springframework.security=trace
logging.level.org.springframework.security.oauth2=trace
