scrape_configs:
  - job_name: 'magjob-backend-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['magjob-backend:8080']
        labels:
          application: 'magjob-backend'
