version: "3.9"
services:
  keycloak:
    container_name: keycloak
    build:
      context: .
    command: start-dev --import-realm
    environment:
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ${APPDATA}/db/keycloak2:/opt/keycloak/data
      - ./magjob-realm.json:/opt/keycloak/data/import/magjob-realm.json
    ports:
      - "8180:8080"

networks:
  local:
    name: local
    driver: bridge