name: magjob CI with Maven, NodeJS and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud-scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonarcloud-scan-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=KeepIt-Up_MagJob

  build-and-deploy-to-registry-backend:
    needs: [ sonar-cloud-scan-backend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: 17
            cache: maven
      - name: Grant execute permission for mvn
        run: chmod +x mvn
      - name: Build with Maven
        run: mvn verify
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
            image: keepitup2023/magjob-backend:latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

  build-and-deploy-to-registry-frontend:
    needs: [ sonar-cloud-scan-frontend ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
         node-version: 21
      - name: Grant execute permission for npm
        run: chmod +x npm
      - name: Install dependencies with npm
        run: npm install
      - name: Test with npm
        run: npm test
      - name: Build with npm
        run: npm run build
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: keepitup2023/magjob-frontend:latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  #update-config-repository:
  #  needs: [ build-and-deploy-to-registry-backend, build-and-deploy-to-registry-frontend ]
  #  runs-on: ubuntu-latest
  #  steps: