name: magjob grafana CI

on:
  push:
    branches: [ main ]
    paths:
      - images/grafana/**
  workflow_dispatch:

jobs:
  build-and-deploy-to-registry-grafana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: keepitup2023/magjob-grafana
            tags: latest
            registry: docker.io
            dockerfile: images/grafana/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
