name: magjob keycloak CI

on:
  push:
    branches: [ main ]
    paths:
      - images/keycloak/**
  workflow_dispatch:

jobs:
  build-and-deploy-to-registry-keycloak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
            image: keepitup2023/magjob-keycloak:latest
            registry: docker.io
            dockerfile: images/keycloak/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
